stages:
  download_data:
    cmd: python3 src/data/download_from_inat.py
    deps:
    - data/raw/monkeys.csv
    - src/data/download_from_inat.py
    outs:
    - data/processed/images
  preprocess_data:
    cmd: python3 src/data/preprocess.py
    deps:
    - data/processed/images
    - src/data/preprocess.py
    outs:
    - data/processed/ready
  train_model:
    cmd: python3 src/train.py --outs models/resnet18.pt
    deps:
    - data/processed/ready
    - src/data/dataset.py
    - src/models/resnet18.py
    - src/train.py
    params:
    - train
    outs:
    - models/resnet18.pt
    metrics:
    - metrics.json
